### ISSUE TITLE
MIT Logo too small

### ISSUE THREAD

**Issue by nicolelf** [dhmit/dhmit-site#10]
From MIT Communications Strategist: "On your website, the MIT logo at the top right should be a bit larger, and the full name is difficult to read. I’d recommend using just the MIT logo (without Massachusetts Institute of Technology). It’s great that you have the complete logo in the footer."

**Comment by mscuthbert** [comment]
The question is whether to fix this now or know that it'll get fixed on the new version?

**Comment by ryaanahmed** [comment]
> The question is whether to fix this now or know that it'll get fixed on the new version?

Since we won't have the new site for a couple months yet (late Feb delivery), I think this can be a low priority item for @nicolelf in any downtime over the break.

**Comment by ryaanahmed** [comment]
Closed via #13
