### ISSUE TITLE
Replace Reading Redux portrait of Sandy with the project image

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/dhmit-site#14]
@nicolelf -- could you replace the image of Sandy with the image that we licensed for the project? Thanks!

**Comment by ryaanahmed** [comment]
@Crista2019 -- since you're on other website tasks, could you do this also?

**Comment by Crista2019** [comment]
@ryaanahmed No problem! Where could I find the picture?

**Comment by ryaanahmed** [comment]
You can grab the copy off the landing page at https://rereading.dhmit.xyz/

(Might be too high res -- you might want to scale it down a bit.) Thanks!

**Comment by Crista2019** [comment]
Ok, great. I can do that!
